exp = dict()

# %% knit_005

# flip img
exp['knit005_201029_exp1_v1'] = {'ref': 'knit_005', 'date': 201029, 'nexp': 1,
                                 'version_raw': 1, 'version_work': 1,
                                 'vitesse': 0.005, 'Lw_0': 170, 'Lw_i': 210, 'Lw_max': 219.99,
                                 'fr_instron': 25, 'sursample': False,
                                 'delta_z': 1, 'delta_t_pict': 5,
                                 'nb_point_eff': 1,
                                 'prescycle': 2, 'mincycle': 2, 'maxcycle': 31,
                                 'mix_set': False, 'nb_set': 1, 'img': True, 'red': False,
                                 'nb_process': 15,
                                 'config_corr_fraction': 10,

                                 'config_scalarevent_flu_exposants': [5, 4, 4, 3, 3, 3],
                                 'config_scalarevent_flu_seuils': [3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 5e-3],
                                 'config_scalarevent_flu_save_seuils': ['3_5', '1_4', '3_4', '1_3', '3_3', '5_3'],
                                 'config_scalarevent_flu_nb_seuils': 6,
                                 'config_scalarevent_flu_which_seuil': 2,
                                 'config_scalarevent_flu_Sm_which_seuil': 5,
                                 'config_scalarevent_flu_nbclasses': 3,

                                 'config_imgevent_flu_slip_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_slip_seuils': [3e-4, 1e-3, 2e-3, 3e-3, 4e-3, 1e-2],
                                 'config_imgevent_flu_slip_save_seuils': ['3_4', '1_3', '2_3', '3_3', '4_3', '1_2'],
                                 'config_imgevent_flu_slip_which_seuil': 2,
                                 'config_imgevent_flu_slip_nb_seuils': 6,

                                 'config_imgevent_flu_sepvort_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_sepvort_seuils': [3e-4, 2e-3, 3e-3, 4e-3, 5e-3, 1e-2],
                                 'config_imgevent_flu_sepvort_save_seuils': ['3_4', '2_3', '3_3', '4_3', '5_3', '1_2'],
                                 'config_imgevent_flu_sepvort_which_seuil': 2,
                                 'config_imgevent_flu_sepvort_nb_seuils': 6,

                                 'config_imgevent_flu_exposants': [3, 3, 3],
                                 'config_imgevent_flu_seuils': [2e-3, 3e-3, 5e-3],
                                 'config_imgevent_flu_save_seuils': ['2_3', '3_3', '5_3'],
                                 'config_imgevent_flu_which_seuil': 2,
                                 'config_imgevent_flu_nb_seuils': 3,
                                 }

exp['knit005_201029_exp2_v1'] = {'ref': 'knit_005', 'date': 201029, 'nexp': 2,
                                 'version_raw': 1, 'version_work': 1,
                                 'vitesse': 0.005, 'Lw_0': 170, 'Lw_i': 210, 'Lw_max': 219.99,
                                 'fr_instron': 25, 'sursample': False,
                                 'delta_z': 1, 'delta_t_pict': 5,
                                 'nb_point_eff': 1,
                                 'prescycle': 2, 'mincycle': 2, 'maxcycle': 39,
                                 'mix_set': False, 'nb_set': 1, 'img': True, 'red': False,
                                 'nb_process': 15,
                                 'config_corr_fraction': 10,

                                 'config_scalarevent_flu_exposants': [5, 4, 4, 3, 3, 3],
                                 'config_scalarevent_flu_seuils': [3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 5e-3],
                                 'config_scalarevent_flu_save_seuils': ['3_5', '1_4', '3_4', '1_3', '3_3', '5_3'],
                                 'config_scalarevent_flu_nb_seuils': 6,
                                 'config_scalarevent_flu_which_seuil': 2,
                                 'config_scalarevent_flu_Sm_which_seuil': 5,
                                 'config_scalarevent_flu_nbclasses': 3,

                                 'config_imgevent_flu_slip_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_slip_seuils': [3e-4, 1e-3, 2e-3, 3e-3, 4e-3, 1e-2],
                                 'config_imgevent_flu_slip_save_seuils': ['3_4', '1_3', '2_3', '3_3', '4_3', '1_2'],
                                 'config_imgevent_flu_slip_which_seuil': 2,
                                 'config_imgevent_flu_slip_nb_seuils': 6,

                                 'config_imgevent_flu_sepvort_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_sepvort_seuils': [3e-4, 2e-3, 3e-3, 4e-3, 5e-3, 1e-2],
                                 'config_imgevent_flu_sepvort_save_seuils': ['3_4', '2_3', '3_3', '4_3', '5_3', '1_2'],
                                 'config_imgevent_flu_sepvort_which_seuil': 2,
                                 'config_imgevent_flu_sepvort_nb_seuils': 6,

                                 'config_imgevent_flu_exposants': [3, 3, 3],
                                 'config_imgevent_flu_seuils': [2e-3, 3e-3, 5e-3],
                                 'config_imgevent_flu_save_seuils': ['2_3', '3_3', '5_3'],
                                 'config_imgevent_flu_which_seuil': 2,
                                 'config_imgevent_flu_nb_seuils': 3,
                                 }

exp['knit005_201029_exp3_v1'] = {'ref': 'knit_005', 'date': 201029, 'nexp': 3,
                                 'version_raw': 1, 'version_work': 1,
                                 'vitesse': 0.005, 'Lw_0': 170, 'Lw_i': 210, 'Lw_max': 219.99,
                                 'fr_instron': 25, 'sursample': False,
                                 'delta_z': 1, 'delta_t_pict': 5,
                                 'nb_point_eff': 1,
                                 'prescycle': 2, 'mincycle': 2, 'maxcycle': 36,
                                 'mix_set': False, 'nb_set': 1, 'img': True, 'red': False,
                                 'nb_process': 15,
                                 'config_corr_fraction': 10,

                                 'config_scalarevent_flu_exposants': [5, 4, 4, 3, 3, 3],
                                 'config_scalarevent_flu_seuils': [3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 5e-3],
                                 'config_scalarevent_flu_save_seuils': ['3_5', '1_4', '3_4', '1_3', '3_3', '5_3'],
                                 'config_scalarevent_flu_nb_seuils': 6,
                                 'config_scalarevent_flu_which_seuil': 2,
                                 'config_scalarevent_flu_Sm_which_seuil': 5,
                                 'config_scalarevent_flu_nbclasses': 3,

                                 'config_imgevent_flu_slip_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_slip_seuils': [3e-4, 1e-3, 2e-3, 3e-3, 4e-3, 1e-2],
                                 'config_imgevent_flu_slip_save_seuils': ['3_4', '1_3', '2_3', '3_3', '4_3', '1_2'],
                                 'config_imgevent_flu_slip_which_seuil': 2,
                                 'config_imgevent_flu_slip_nb_seuils': 6,

                                 'config_imgevent_flu_sepvort_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_sepvort_seuils': [3e-4, 2e-3, 3e-3, 4e-3, 5e-3, 1e-2],
                                 'config_imgevent_flu_sepvort_save_seuils': ['3_4', '2_3', '3_3', '4_3', '5_3', '1_2'],
                                 'config_imgevent_flu_sepvort_which_seuil': 2,
                                 'config_imgevent_flu_sepvort_nb_seuils': 6,

                                 'config_imgevent_flu_exposants': [3, 3, 3],
                                 'config_imgevent_flu_seuils': [2e-3, 3e-3, 5e-3],
                                 'config_imgevent_flu_save_seuils': ['2_3', '3_3', '5_3'],
                                 'config_imgevent_flu_which_seuil': 2,
                                 'config_imgevent_flu_nb_seuils': 3,
                                 }

exp['knit005_201029_exp4_v1'] = {'ref': 'knit_005', 'date': 201029, 'nexp': 4,
                                 'version_raw': 1, 'version_work': 1,
                                 'vitesse': 0.005, 'Lw_0': 170, 'Lw_i': 210, 'Lw_max': 219.99,
                                 'fr_instron': 25, 'sursample': False,
                                 'delta_z': 1, 'delta_t_pict': 5,
                                 'nb_point_eff': 1,
                                 'prescycle': 2, 'mincycle': 2, 'maxcycle': 36,
                                 'mix_set': False, 'nb_set': 1, 'img': True, 'red': False,
                                 'nb_process': 15,
                                 'config_corr_fraction': 10,

                                 'config_scalarevent_flu_exposants': [5, 4, 4, 3, 3, 3],
                                 'config_scalarevent_flu_seuils': [3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 5e-3],
                                 'config_scalarevent_flu_save_seuils': ['3_5', '1_4', '3_4', '1_3', '3_3', '5_3'],
                                 'config_scalarevent_flu_nb_seuils': 6,
                                 'config_scalarevent_flu_which_seuil': 2,
                                 'config_scalarevent_flu_Sm_which_seuil': 5,
                                 'config_scalarevent_flu_nbclasses': 3,

                                 'config_imgevent_flu_slip_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_slip_seuils': [3e-4, 1e-3, 2e-3, 3e-3, 4e-3, 1e-2],
                                 'config_imgevent_flu_slip_save_seuils': ['3_4', '1_3', '2_3', '3_3', '4_3', '1_2'],
                                 'config_imgevent_flu_slip_which_seuil': 2,
                                 'config_imgevent_flu_slip_nb_seuils': 6,

                                 'config_imgevent_flu_sepvort_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_sepvort_seuils': [3e-4, 2e-3, 3e-3, 4e-3, 5e-3, 1e-2],
                                 'config_imgevent_flu_sepvort_save_seuils': ['3_4', '2_3', '3_3', '4_3', '5_3', '1_2'],
                                 'config_imgevent_flu_sepvort_which_seuil': 2,
                                 'config_imgevent_flu_sepvort_nb_seuils': 6,

                                 'config_imgevent_flu_exposants': [3, 3, 3],
                                 'config_imgevent_flu_seuils': [2e-3, 3e-3, 5e-3],
                                 'config_imgevent_flu_save_seuils': ['2_3', '3_3', '5_3'],
                                 'config_imgevent_flu_which_seuil': 2,
                                 'config_imgevent_flu_nb_seuils': 3,
                                 }

exp['knit005_201029_exp5_v1'] = {'ref': 'knit_005', 'date': 201029, 'nexp': 5,
                                 'version_raw': 1, 'version_work': 1,
                                 'vitesse': 0.005, 'Lw_0': 170, 'Lw_i': 210, 'Lw_max': 219.99,
                                 'fr_instron': 25, 'sursample': False,
                                 'delta_z': 1, 'delta_t_pict': 5,
                                 'nb_point_eff': 1,
                                 'prescycle': 2, 'mincycle': 2, 'maxcycle': 31,
                                 'mix_set': False, 'nb_set': 1, 'img': True, 'red': False,
                                 'nb_process': 15,
                                 'config_corr_fraction': 10,

                                 'config_scalarevent_flu_exposants': [5, 4, 4, 3, 3, 3],
                                 'config_scalarevent_flu_seuils': [3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 5e-3],
                                 'config_scalarevent_flu_save_seuils': ['3_5', '1_4', '3_4', '1_3', '3_3', '5_3'],
                                 'config_scalarevent_flu_nb_seuils': 6,
                                 'config_scalarevent_flu_which_seuil': 2,
                                 'config_scalarevent_flu_Sm_which_seuil': 5,
                                 'config_scalarevent_flu_nbclasses': 3,

                                 'config_imgevent_flu_slip_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_slip_seuils': [3e-4, 1e-3, 2e-3, 3e-3, 4e-3, 1e-2],
                                 'config_imgevent_flu_slip_save_seuils': ['3_4', '1_3', '2_3', '3_3', '4_3', '1_2'],
                                 'config_imgevent_flu_slip_which_seuil': 2,
                                 'config_imgevent_flu_slip_nb_seuils': 6,

                                 'config_imgevent_flu_sepvort_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_sepvort_seuils': [3e-4, 2e-3, 3e-3, 4e-3, 5e-3, 1e-2],
                                 'config_imgevent_flu_sepvort_save_seuils': ['3_4', '2_3', '3_3', '4_3', '5_3', '1_2'],
                                 'config_imgevent_flu_sepvort_which_seuil': 2,
                                 'config_imgevent_flu_sepvort_nb_seuils': 6,

                                 'config_imgevent_flu_exposants': [3, 3, 3],
                                 'config_imgevent_flu_seuils': [2e-3, 3e-3, 5e-3],
                                 'config_imgevent_flu_save_seuils': ['2_3', '3_3', '5_3'],
                                 'config_imgevent_flu_which_seuil': 2,
                                 'config_imgevent_flu_nb_seuils': 3,
                                 }

exp['knit005_201029_exp6_v1'] = {'ref': 'knit_005', 'date': 201029, 'nexp': 6,
                                 'version_raw': 1, 'version_work': 1,
                                 'vitesse': 0.005, 'Lw_0': 170, 'Lw_i': 210, 'Lw_max': 219.99,
                                 'fr_instron': 25, 'sursample': False,
                                 'delta_z': 1, 'delta_t_pict': 5,
                                 'nb_point_eff': 1,
                                 'prescycle': 2, 'mincycle': 2, 'maxcycle': 31,
                                 'mix_set': False, 'nb_set': 1, 'img': False, 'red': False,
                                 'nb_process': 15,
                                 'config_corr_fraction': 10,

                                 'config_scalarevent_flu_exposants': [5, 4, 4, 3, 3, 3],
                                 'config_scalarevent_flu_seuils': [3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 5e-3],
                                 'config_scalarevent_flu_save_seuils': ['3_5', '1_4', '3_4', '1_3', '3_3', '5_3'],
                                 'config_scalarevent_flu_nb_seuils': 6,
                                 'config_scalarevent_flu_which_seuil': 2,
                                 'config_scalarevent_flu_Sm_which_seuil': 5,
                                 'config_scalarevent_flu_nbclasses': 3,

                                 'config_imgevent_flu_slip_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_slip_seuils': [3e-4, 1e-3, 2e-3, 3e-3, 4e-3, 1e-2],
                                 'config_imgevent_flu_slip_save_seuils': ['3_4', '1_3', '2_3', '3_3', '4_3', '1_2'],
                                 'config_imgevent_flu_slip_which_seuil': 2,
                                 'config_imgevent_flu_slip_nb_seuils': 6,

                                 'config_imgevent_flu_sepvort_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_sepvort_seuils': [3e-4, 2e-3, 3e-3, 4e-3, 5e-3, 1e-2],
                                 'config_imgevent_flu_sepvort_save_seuils': ['3_4', '2_3', '3_3', '4_3', '5_3', '1_2'],
                                 'config_imgevent_flu_sepvort_which_seuil': 2,
                                 'config_imgevent_flu_sepvort_nb_seuils': 6,

                                 'config_imgevent_flu_exposants': [3, 3, 3],
                                 'config_imgevent_flu_seuils': [2e-3, 3e-3, 5e-3],
                                 'config_imgevent_flu_save_seuils': ['2_3', '3_3', '5_3'],
                                 'config_imgevent_flu_which_seuil': 2,
                                 'config_imgevent_flu_nb_seuils': 3,
                                 }

exp['knit005_201029_exp7_v1'] = {'ref': 'knit_005', 'date': 201029, 'nexp': 7,
                                 'version_raw': 1, 'version_work': 1,
                                 'vitesse': 0.005, 'Lw_0': 170, 'Lw_i': 210, 'Lw_max': 219.99,
                                 'fr_instron': 25, 'sursample': False,
                                 'delta_z': 1, 'delta_t_pict': 5,
                                 'nb_point_eff': 1,
                                 'prescycle': 2, 'mincycle': 2, 'maxcycle': 23,
                                 'mix_set': False, 'nb_set': 1, 'img': True, 'red': False,
                                 'nb_process': 15,
                                 'config_corr_fraction': 10,

                                 'config_scalarevent_flu_exposants': [5, 4, 4, 3, 3, 3],
                                 'config_scalarevent_flu_seuils': [3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 5e-3],
                                 'config_scalarevent_flu_save_seuils': ['3_5', '1_4', '3_4', '1_3', '3_3', '5_3'],
                                 'config_scalarevent_flu_nb_seuils': 6,
                                 'config_scalarevent_flu_which_seuil': 2,
                                 'config_scalarevent_flu_Sm_which_seuil': 5,
                                 'config_scalarevent_flu_nbclasses': 3,

                                 'config_imgevent_flu_slip_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_slip_seuils': [3e-4, 1e-3, 2e-3, 3e-3, 4e-3, 1e-2],
                                 'config_imgevent_flu_slip_save_seuils': ['3_4', '1_3', '2_3', '3_3', '4_3', '1_2'],
                                 'config_imgevent_flu_slip_which_seuil': 2,
                                 'config_imgevent_flu_slip_nb_seuils': 6,

                                 'config_imgevent_flu_sepvort_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_sepvort_seuils': [3e-4, 2e-3, 3e-3, 4e-3, 5e-3, 1e-2],
                                 'config_imgevent_flu_sepvort_save_seuils': ['3_4', '2_3', '3_3', '4_3', '5_3', '1_2'],
                                 'config_imgevent_flu_sepvort_which_seuil': 2,
                                 'config_imgevent_flu_sepvort_nb_seuils': 6,

                                 'config_imgevent_flu_exposants': [3, 3, 3],
                                 'config_imgevent_flu_seuils': [2e-3, 3e-3, 5e-3],
                                 'config_imgevent_flu_save_seuils': ['2_3', '3_3', '5_3'],
                                 'config_imgevent_flu_which_seuil': 2,
                                 'config_imgevent_flu_nb_seuils': 3,
                                 }

exp['knit005_201029_exp8_v1'] = {'ref': 'knit_005', 'date': 201029, 'nexp': 8,
                                 'version_raw': 1, 'version_work': 1,
                                 'vitesse': 0.005, 'Lw_0': 170, 'Lw_i': 210, 'Lw_max': 219.99,
                                 'fr_instron': 25, 'sursample': False,
                                 'delta_z': 1, 'delta_t_pict': 5,
                                 'nb_point_eff': 1,
                                 'prescycle': 2, 'mincycle': 2, 'maxcycle': 27,
                                 'mix_set': False, 'nb_set': 1, 'img': False, 'red': False,
                                 'nb_process': 15,
                                 'config_corr_fraction': 10,

                                 'config_scalarevent_flu_exposants': [5, 4, 4, 3, 3, 3],
                                 'config_scalarevent_flu_seuils': [3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 5e-3],
                                 'config_scalarevent_flu_save_seuils': ['3_5', '1_4', '3_4', '1_3', '3_3', '5_3'],
                                 'config_scalarevent_flu_nb_seuils': 6,
                                 'config_scalarevent_flu_which_seuil': 2,
                                 'config_scalarevent_flu_Sm_which_seuil': 5,
                                 'config_scalarevent_flu_nbclasses': 3,

                                 'config_imgevent_flu_slip_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_slip_seuils': [3e-4, 1e-3, 2e-3, 3e-3, 4e-3, 1e-2],
                                 'config_imgevent_flu_slip_save_seuils': ['3_4', '1_3', '2_3', '3_3', '4_3', '1_2'],
                                 'config_imgevent_flu_slip_which_seuil': 2,
                                 'config_imgevent_flu_slip_nb_seuils': 6,

                                 'config_imgevent_flu_sepvort_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_sepvort_seuils': [3e-4, 2e-3, 3e-3, 4e-3, 5e-3, 1e-2],
                                 'config_imgevent_flu_sepvort_save_seuils': ['3_4', '2_3', '3_3', '4_3', '5_3', '1_2'],
                                 'config_imgevent_flu_sepvort_which_seuil': 2,
                                 'config_imgevent_flu_sepvort_nb_seuils': 6,

                                 'config_imgevent_flu_exposants': [3, 3, 3],
                                 'config_imgevent_flu_seuils': [2e-3, 3e-3, 5e-3],
                                 'config_imgevent_flu_save_seuils': ['2_3', '3_3', '5_3'],
                                 'config_imgevent_flu_which_seuil': 2,
                                 'config_imgevent_flu_nb_seuils': 3,
                                 }

exp['knit005_201029_exp9_v1'] = {'ref': 'knit_005', 'date': 201029, 'nexp': 9,
                                 'version_raw': 1, 'version_work': 1,
                                 'vitesse': 0.005, 'Lw_0': 170, 'Lw_i': 210, 'Lw_max': 219.99,
                                 'fr_instron': 25, 'sursample': False,
                                 'delta_z': 1, 'delta_t_pict': 5,
                                 'nb_point_eff': 1,
                                 'prescycle': 2, 'mincycle': 2, 'maxcycle': 17,
                                 'mix_set': False, 'nb_set': 1, 'img': True, 'red': False,
                                 'nb_process': 15,
                                 'config_corr_fraction': 10,

                                 'config_scalarevent_flu_exposants': [5, 4, 4, 3, 3, 3],
                                 'config_scalarevent_flu_seuils': [3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 5e-3],
                                 'config_scalarevent_flu_save_seuils': ['3_5', '1_4', '3_4', '1_3', '3_3', '5_3'],
                                 'config_scalarevent_flu_nb_seuils': 6,
                                 'config_scalarevent_flu_which_seuil': 2,
                                 'config_scalarevent_flu_Sm_which_seuil': 5,
                                 'config_scalarevent_flu_nbclasses': 3,

                                 'config_imgevent_flu_slip_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_slip_seuils': [3e-4, 1e-3, 2e-3, 3e-3, 4e-3, 1e-2],
                                 'config_imgevent_flu_slip_save_seuils': ['3_4', '1_3', '2_3', '3_3', '4_3', '1_2'],
                                 'config_imgevent_flu_slip_which_seuil': 2,
                                 'config_imgevent_flu_slip_nb_seuils': 6,

                                 'config_imgevent_flu_sepvort_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_sepvort_seuils': [3e-4, 2e-3, 3e-3, 4e-3, 5e-3, 1e-2],
                                 'config_imgevent_flu_sepvort_save_seuils': ['3_4', '2_3', '3_3', '4_3', '5_3', '1_2'],
                                 'config_imgevent_flu_sepvort_which_seuil': 2,
                                 'config_imgevent_flu_sepvort_nb_seuils': 6,

                                 'config_imgevent_flu_exposants': [3, 3, 3],
                                 'config_imgevent_flu_seuils': [2e-3, 3e-3, 5e-3],
                                 'config_imgevent_flu_save_seuils': ['2_3', '3_3', '5_3'],
                                 'config_imgevent_flu_which_seuil': 2,
                                 'config_imgevent_flu_nb_seuils': 3,
                                 }

exp['knit005_201116_exp4_v1'] = {'ref': 'knit_005', 'date': 201116, 'nexp': 4,
                                 'version_raw': 1, 'version_work': 1,
                                 'vitesse': 0.005, 'Lw_0': 170, 'Lw_i': 210, 'Lw_max': 219.99,
                                 'fr_instron': 25, 'sursample': False,
                                 'delta_z': 1, 'delta_t_pict': 5,
                                 'nb_point_eff': 1,
                                 'prescycle': 2, 'mincycle': 2, 'maxcycle': 39,
                                 'mix_set': False, 'nb_set': 1, 'img': False, 'red': False,
                                 'nb_process': 15,
                                 'config_corr_fraction': 10,

                                 'config_scalarevent_flu_exposants': [5, 4, 4, 3, 3, 3],
                                 'config_scalarevent_flu_seuils': [3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 5e-3],
                                 'config_scalarevent_flu_save_seuils': ['3_5', '1_4', '3_4', '1_3', '3_3', '5_3'],
                                 'config_scalarevent_flu_nb_seuils': 6,
                                 'config_scalarevent_flu_which_seuil': 2,
                                 'config_scalarevent_flu_Sm_which_seuil': 5,
                                 'config_scalarevent_flu_nbclasses': 3,

                                 'config_imgevent_flu_slip_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_slip_seuils': [3e-4, 1e-3, 2e-3, 3e-3, 4e-3, 1e-2],
                                 'config_imgevent_flu_slip_save_seuils': ['3_4', '1_3', '2_3', '3_3', '4_3', '1_2'],
                                 'config_imgevent_flu_slip_which_seuil': 2,
                                 'config_imgevent_flu_slip_nb_seuils': 6,

                                 'config_imgevent_flu_sepvort_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_sepvort_seuils': [3e-4, 2e-3, 3e-3, 4e-3, 5e-3, 1e-2],
                                 'config_imgevent_flu_sepvort_save_seuils': ['3_4', '2_3', '3_3', '4_3', '5_3', '1_2'],
                                 'config_imgevent_flu_sepvort_which_seuil': 2,
                                 'config_imgevent_flu_sepvort_nb_seuils': 6,

                                 'config_imgevent_flu_exposants': [3, 3, 3],
                                 'config_imgevent_flu_seuils': [2e-3, 3e-3, 5e-3],
                                 'config_imgevent_flu_save_seuils': ['2_3', '3_3', '5_3'],
                                 'config_imgevent_flu_which_seuil': 2,
                                 'config_imgevent_flu_nb_seuils': 3,
                                 }

exp['knit005_201119_exp1_v1'] = {'ref': 'knit_005', 'date': 201119, 'nexp': 1,
                                 'version_raw': 1, 'version_work': 1,
                                 'vitesse': 0.005, 'Lw_0': 170, 'Lw_i': 210, 'Lw_max': 219.99,
                                 'fr_instron': 25, 'sursample': False,
                                 'delta_z': 1, 'delta_t_pict': 5,
                                 'nb_point_eff': 1,
                                 'prescycle': 2, 'mincycle': 2, 'maxcycle': 36,
                                 'mix_set': False, 'nb_set': 1, 'img': True, 'red': False,
                                 'nb_process': 15,
                                 'config_corr_fraction': 10,

                                 'config_scalarevent_flu_exposants': [5, 4, 4, 3, 3, 3],
                                 'config_scalarevent_flu_seuils': [3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 5e-3],
                                 'config_scalarevent_flu_save_seuils': ['3_5', '1_4', '3_4', '1_3', '3_3', '5_3'],
                                 'config_scalarevent_flu_nb_seuils': 6,
                                 'config_scalarevent_flu_which_seuil': 2,
                                 'config_scalarevent_flu_Sm_which_seuil': 5,
                                 'config_scalarevent_flu_nbclasses': 3,

                                 'config_imgevent_flu_slip_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_slip_seuils': [3e-4, 1e-3, 2e-3, 3e-3, 4e-3, 1e-2],
                                 'config_imgevent_flu_slip_save_seuils': ['3_4', '1_3', '2_3', '3_3', '4_3', '1_2'],
                                 'config_imgevent_flu_slip_which_seuil': 2,
                                 'config_imgevent_flu_slip_nb_seuils': 6,

                                 'config_imgevent_flu_sepvort_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_sepvort_seuils': [3e-4, 2e-3, 3e-3, 4e-3, 5e-3, 1e-2],
                                 'config_imgevent_flu_sepvort_save_seuils': ['3_4', '2_3', '3_3', '4_3', '5_3', '1_2'],
                                 'config_imgevent_flu_sepvort_which_seuil': 2,
                                 'config_imgevent_flu_sepvort_nb_seuils': 6,

                                 'config_imgevent_flu_exposants': [3, 3, 3],
                                 'config_imgevent_flu_seuils': [2e-3, 3e-3, 5e-3],
                                 'config_imgevent_flu_save_seuils': ['2_3', '3_3', '5_3'],
                                 'config_imgevent_flu_which_seuil': 2,
                                 'config_imgevent_flu_nb_seuils': 3,
                                 }

exp['knit005_201119_exp2_v1'] = {'ref': 'knit_005', 'date': 201119, 'nexp': 2,
                                 'version_raw': 1, 'version_work': 1,
                                 'vitesse': 0.005, 'Lw_0': 170, 'Lw_i': 210, 'Lw_max': 219.99,
                                 'fr_instron': 25, 'sursample': False,
                                 'delta_z': 1, 'delta_t_pict': 5,
                                 'nb_point_eff': 1,
                                 'prescycle': 2, 'mincycle': 2, 'maxcycle': 39,
                                 'mix_set': False, 'nb_set': 1, 'img': False, 'red': False,
                                 'nb_process': 15,
                                 'config_corr_fraction': 10,

                                 'config_scalarevent_flu_exposants': [5, 4, 4, 3, 3, 3],
                                 'config_scalarevent_flu_seuils': [3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 5e-3],
                                 'config_scalarevent_flu_save_seuils': ['3_5', '1_4', '3_4', '1_3', '3_3', '5_3'],
                                 'config_scalarevent_flu_nb_seuils': 6,
                                 'config_scalarevent_flu_which_seuil': 2,
                                 'config_scalarevent_flu_Sm_which_seuil': 5,
                                 'config_scalarevent_flu_nbclasses': 3,

                                 'config_imgevent_flu_slip_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_slip_seuils': [3e-4, 1e-3, 2e-3, 3e-3, 4e-3, 1e-2],
                                 'config_imgevent_flu_slip_save_seuils': ['3_4', '1_3', '2_3', '3_3', '4_3', '1_2'],
                                 'config_imgevent_flu_slip_which_seuil': 2,
                                 'config_imgevent_flu_slip_nb_seuils': 6,

                                 'config_imgevent_flu_sepvort_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_sepvort_seuils': [3e-4, 2e-3, 3e-3, 4e-3, 5e-3, 1e-2],
                                 'config_imgevent_flu_sepvort_save_seuils': ['3_4', '2_3', '3_3', '4_3', '5_3', '1_2'],
                                 'config_imgevent_flu_sepvort_which_seuil': 2,
                                 'config_imgevent_flu_sepvort_nb_seuils': 6,

                                 'config_imgevent_flu_exposants': [3, 3, 3],
                                 'config_imgevent_flu_seuils': [2e-3, 3e-3, 5e-3],
                                 'config_imgevent_flu_save_seuils': ['2_3', '3_3', '5_3'],
                                 'config_imgevent_flu_which_seuil': 2,
                                 'config_imgevent_flu_nb_seuils': 3,
                                 }

exp['knit005_201119_exp3_v1'] = {'ref': 'knit_005', 'date': 201119, 'nexp': 3,
                                 'version_raw': 1, 'version_work': 1,
                                 'vitesse': 0.005, 'Lw_0': 170, 'Lw_i': 210, 'Lw_max': 219.99,
                                 'fr_instron': 25, 'sursample': False,
                                 'delta_z': 1, 'delta_t_pict': 5,
                                 'nb_point_eff': 1,
                                 'prescycle': 2, 'mincycle': 2, 'maxcycle': 39,
                                 'mix_set': False, 'nb_set': 1, 'img': True, 'red': False,
                                 'nb_process': 15,
                                 'config_corr_fraction': 10,

                                 'config_scalarevent_flu_exposants': [5, 4, 4, 3, 3, 3],
                                 'config_scalarevent_flu_seuils': [3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 5e-3],
                                 'config_scalarevent_flu_save_seuils': ['3_5', '1_4', '3_4', '1_3', '3_3', '5_3'],
                                 'config_scalarevent_flu_nb_seuils': 6,
                                 'config_scalarevent_flu_which_seuil': 2,
                                 'config_scalarevent_flu_Sm_which_seuil': 5,
                                 'config_scalarevent_flu_nbclasses': 3,

                                 'config_imgevent_flu_slip_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_slip_seuils': [3e-4, 1e-3, 2e-3, 3e-3, 4e-3, 1e-2],
                                 'config_imgevent_flu_slip_save_seuils': ['3_4', '1_3', '2_3', '3_3', '4_3', '1_2'],
                                 'config_imgevent_flu_slip_which_seuil': 2,
                                 'config_imgevent_flu_slip_nb_seuils': 6,

                                 'config_imgevent_flu_sepvort_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_sepvort_seuils': [3e-4, 2e-3, 3e-3, 4e-3, 5e-3, 1e-2],
                                 'config_imgevent_flu_sepvort_save_seuils': ['3_4', '2_3', '3_3', '4_3', '5_3', '1_2'],
                                 'config_imgevent_flu_sepvort_which_seuil': 2,
                                 'config_imgevent_flu_sepvort_nb_seuils': 6,

                                 'config_imgevent_flu_exposants': [3, 3, 3],
                                 'config_imgevent_flu_seuils': [2e-3, 3e-3, 5e-3],
                                 'config_imgevent_flu_save_seuils': ['2_3', '3_3', '5_3'],
                                 'config_imgevent_flu_which_seuil': 2,
                                 'config_imgevent_flu_nb_seuils': 3,
                                 }

exp['knit005_201119_exp4_v1'] = {'ref': 'knit_005', 'date': 201119, 'nexp': 4,
                                 'version_raw': 1, 'version_work': 1,
                                 'vitesse': 0.005, 'Lw_0': 170, 'Lw_i': 210, 'Lw_max': 219.99,
                                 'fr_instron': 25, 'sursample': False,
                                 'delta_z': 1, 'delta_t_pict': 5,
                                 'nb_point_eff': 1,
                                 'prescycle': 2, 'mincycle': 2, 'maxcycle': 39,
                                 'mix_set': False, 'nb_set': 1, 'img': True, 'red': False,
                                 'nb_process': 15,
                                 'config_corr_fraction': 10,

                                 'config_scalarevent_flu_exposants': [5, 4, 4, 3, 3, 3],
                                 'config_scalarevent_flu_seuils': [3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 5e-3],
                                 'config_scalarevent_flu_save_seuils': ['3_5', '1_4', '3_4', '1_3', '3_3', '5_3'],
                                 'config_scalarevent_flu_nb_seuils': 6,
                                 'config_scalarevent_flu_which_seuil': 2,
                                 'config_scalarevent_flu_Sm_which_seuil': 5,
                                 'config_scalarevent_flu_nbclasses': 3,

                                 'config_imgevent_flu_slip_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_slip_seuils': [3e-4, 1e-3, 2e-3, 3e-3, 4e-3, 1e-2],
                                 'config_imgevent_flu_slip_save_seuils': ['3_4', '1_3', '2_3', '3_3', '4_3', '1_2'],
                                 'config_imgevent_flu_slip_which_seuil': 2,
                                 'config_imgevent_flu_slip_nb_seuils': 6,

                                 'config_imgevent_flu_sepvort_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_sepvort_seuils': [3e-4, 2e-3, 3e-3, 4e-3, 5e-3, 1e-2],
                                 'config_imgevent_flu_sepvort_save_seuils': ['3_4', '2_3', '3_3', '4_3', '5_3', '1_2'],
                                 'config_imgevent_flu_sepvort_which_seuil': 2,
                                 'config_imgevent_flu_sepvort_nb_seuils': 6,

                                 'config_imgevent_flu_exposants': [3, 3, 3],
                                 'config_imgevent_flu_seuils': [2e-3, 3e-3, 5e-3],
                                 'config_imgevent_flu_save_seuils': ['2_3', '3_3', '5_3'],
                                 'config_imgevent_flu_which_seuil': 2,
                                 'config_imgevent_flu_nb_seuils': 3,
                                 }

exp['knit005_201119_exp5_v1'] = {'ref': 'knit_005', 'date': 201119, 'nexp': 5,
                                 'version_raw': 1, 'version_work': 1,
                                 'vitesse': 0.005, 'Lw_0': 170, 'Lw_i': 210, 'Lw_max': 219.99,
                                 'fr_instron': 25, 'sursample': False,
                                 'delta_z': 1, 'delta_t_pict': 5,
                                 'nb_point_eff': 1,
                                 'prescycle': 2, 'mincycle': 2, 'maxcycle': 31,
                                 'mix_set': False, 'nb_set': 1, 'img': False, 'red': False,
                                 'nb_process': 15,
                                 'config_corr_fraction': 10,

                                 'config_scalarevent_flu_exposants': [5, 4, 4, 3, 3, 3],
                                 'config_scalarevent_flu_seuils': [3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 5e-3],
                                 'config_scalarevent_flu_save_seuils': ['3_5', '1_4', '3_4', '1_3', '3_3', '5_3'],
                                 'config_scalarevent_flu_nb_seuils': 6,
                                 'config_scalarevent_flu_which_seuil': 2,
                                 'config_scalarevent_flu_Sm_which_seuil': 5,
                                 'config_scalarevent_flu_nbclasses': 3,

                                 'config_imgevent_flu_slip_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_slip_seuils': [3e-4, 1e-3, 2e-3, 3e-3, 4e-3, 1e-2],
                                 'config_imgevent_flu_slip_save_seuils': ['3_4', '1_3', '2_3', '3_3', '4_3', '1_2'],
                                 'config_imgevent_flu_slip_which_seuil': 2,
                                 'config_imgevent_flu_slip_nb_seuils': 6,

                                 'config_imgevent_flu_sepvort_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_sepvort_seuils': [3e-4, 2e-3, 3e-3, 4e-3, 5e-3, 1e-2],
                                 'config_imgevent_flu_sepvort_save_seuils': ['3_4', '2_3', '3_3', '4_3', '5_3', '1_2'],
                                 'config_imgevent_flu_sepvort_which_seuil': 2,
                                 'config_imgevent_flu_sepvort_nb_seuils': 6,

                                 'config_imgevent_flu_exposants': [3, 3, 3],
                                 'config_imgevent_flu_seuils': [2e-3, 3e-3, 5e-3],
                                 'config_imgevent_flu_save_seuils': ['2_3', '3_3', '5_3'],
                                 'config_imgevent_flu_which_seuil': 2,
                                 'config_imgevent_flu_nb_seuils': 3,
                                 }

exp['knit005_201119_exp6_v1'] = {'ref': 'knit_005', 'date': 201119, 'nexp': 6,
                                 'version_raw': 1, 'version_work': 1,
                                 'vitesse': 0.005, 'Lw_0': 170, 'Lw_i': 210, 'Lw_max': 219.99,
                                 'fr_instron': 25, 'sursample': False,
                                 'delta_z': 1, 'delta_t_pict': 5,
                                 'nb_point_eff': 1,
                                 'prescycle': 2, 'mincycle': 2, 'maxcycle': 39,
                                 'mix_set': False, 'nb_set': 1, 'img': True, 'red': False,
                                 'nb_process': 15,
                                 'config_corr_fraction': 10,

                                 'config_scalarevent_flu_exposants': [5, 4, 4, 3, 3, 3],
                                 'config_scalarevent_flu_seuils': [3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 5e-3],
                                 'config_scalarevent_flu_save_seuils': ['3_5', '1_4', '3_4', '1_3', '3_3', '5_3'],
                                 'config_scalarevent_flu_nb_seuils': 6,
                                 'config_scalarevent_flu_which_seuil': 2,
                                 'config_scalarevent_flu_Sm_which_seuil': 5,
                                 'config_scalarevent_flu_nbclasses': 3,

                                 'config_imgevent_flu_slip_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_slip_seuils': [3e-4, 1e-3, 2e-3, 3e-3, 4e-3, 1e-2],
                                 'config_imgevent_flu_slip_save_seuils': ['3_4', '1_3', '2_3', '3_3', '4_3', '1_2'],
                                 'config_imgevent_flu_slip_which_seuil': 2,
                                 'config_imgevent_flu_slip_nb_seuils': 6,

                                 'config_imgevent_flu_sepvort_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_sepvort_seuils': [3e-4, 2e-3, 3e-3, 4e-3, 5e-3, 1e-2],
                                 'config_imgevent_flu_sepvort_save_seuils': ['3_4', '2_3', '3_3', '4_3', '5_3', '1_2'],
                                 'config_imgevent_flu_sepvort_which_seuil': 2,
                                 'config_imgevent_flu_sepvort_nb_seuils': 6,

                                 'config_imgevent_flu_exposants': [3, 3, 3],
                                 'config_imgevent_flu_seuils': [2e-3, 3e-3, 5e-3],
                                 'config_imgevent_flu_save_seuils': ['2_3', '3_3', '5_3'],
                                 'config_imgevent_flu_which_seuil': 2,
                                 'config_imgevent_flu_nb_seuils': 3,
                                 }

exp['knit005_201119_exp7_v1'] = {'ref': 'knit_005', 'date': 201119, 'nexp': 7,
                                 'version_raw': 1, 'version_work': 1,
                                 'vitesse': 0.005, 'Lw_0': 170, 'Lw_i': 210, 'Lw_max': 219.99,
                                 'fr_instron': 25, 'sursample': False,
                                 'delta_z': 1, 'delta_t_pict': 5,
                                 'nb_point_eff': 1,
                                 'prescycle': 2, 'mincycle': 2, 'maxcycle': 33,
                                 'mix_set': False, 'nb_set': 1, 'img': True, 'red': False,
                                 'nb_process': 15,
                                 'config_corr_fraction': 10,

                                 'config_scalarevent_flu_exposants': [5, 4, 4, 3, 3, 3],
                                 'config_scalarevent_flu_seuils': [3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 5e-3],
                                 'config_scalarevent_flu_save_seuils': ['3_5', '1_4', '3_4', '1_3', '3_3', '5_3'],
                                 'config_scalarevent_flu_nb_seuils': 6,
                                 'config_scalarevent_flu_which_seuil': 2,
                                 'config_scalarevent_flu_Sm_which_seuil': 5,
                                 'config_scalarevent_flu_nbclasses': 3,

                                 'config_imgevent_flu_slip_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_slip_seuils': [3e-4, 1e-3, 2e-3, 3e-3, 4e-3, 1e-2],
                                 'config_imgevent_flu_slip_save_seuils': ['3_4', '1_3', '2_3', '3_3', '4_3', '1_2'],
                                 'config_imgevent_flu_slip_which_seuil': 2,
                                 'config_imgevent_flu_slip_nb_seuils': 6,

                                 'config_imgevent_flu_sepvort_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_sepvort_seuils': [3e-4, 2e-3, 3e-3, 4e-3, 5e-3, 1e-2],
                                 'config_imgevent_flu_sepvort_save_seuils': ['3_4', '2_3', '3_3', '4_3', '5_3', '1_2'],
                                 'config_imgevent_flu_sepvort_which_seuil': 2,
                                 'config_imgevent_flu_sepvort_nb_seuils': 6,

                                 'config_imgevent_flu_exposants': [3, 3, 3],
                                 'config_imgevent_flu_seuils': [2e-3, 3e-3, 5e-3],
                                 'config_imgevent_flu_save_seuils': ['2_3', '3_3', '5_3'],
                                 'config_imgevent_flu_which_seuil': 2,
                                 'config_imgevent_flu_nb_seuils': 3,
                                 }

exp['knit005_201119_exp8_v1'] = {'ref': 'knit_005', 'date': 201119, 'nexp': 8,
                                 'version_raw': 1, 'version_work': 1,
                                 'vitesse': 0.005, 'Lw_0': 170, 'Lw_i': 210, 'Lw_max': 219.99,
                                 'fr_instron': 25, 'sursample': False,
                                 'delta_z': 1, 'delta_t_pict': 5,
                                 'nb_point_eff': 1,
                                 'prescycle': 2, 'mincycle': 2, 'maxcycle': 31,
                                 'mix_set': False, 'nb_set': 1, 'img': True, 'red': False,
                                 'nb_process': 15,
                                 'config_corr_fraction': 10,

                                 'config_scalarevent_flu_exposants': [5, 4, 4, 3, 3, 3],
                                 'config_scalarevent_flu_seuils': [3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 5e-3],
                                 'config_scalarevent_flu_save_seuils': ['3_5', '1_4', '3_4', '1_3', '3_3', '5_3'],
                                 'config_scalarevent_flu_nb_seuils': 6,
                                 'config_scalarevent_flu_which_seuil': 2,
                                 'config_scalarevent_flu_Sm_which_seuil': 5,
                                 'config_scalarevent_flu_nbclasses': 3,

                                 'config_imgevent_flu_slip_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_slip_seuils': [3e-4, 1e-3, 2e-3, 3e-3, 4e-3, 1e-2],
                                 'config_imgevent_flu_slip_save_seuils': ['3_4', '1_3', '2_3', '3_3', '4_3', '1_2'],
                                 'config_imgevent_flu_slip_which_seuil': 2,
                                 'config_imgevent_flu_slip_nb_seuils': 6,

                                 'config_imgevent_flu_sepvort_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_sepvort_seuils': [3e-4, 2e-3, 3e-3, 4e-3, 5e-3, 1e-2],
                                 'config_imgevent_flu_sepvort_save_seuils': ['3_4', '2_3', '3_3', '4_3', '5_3', '1_2'],
                                 'config_imgevent_flu_sepvort_which_seuil': 2,
                                 'config_imgevent_flu_sepvort_nb_seuils': 6,

                                 'config_imgevent_flu_exposants': [3, 3, 3],
                                 'config_imgevent_flu_seuils': [2e-3, 3e-3, 5e-3],
                                 'config_imgevent_flu_save_seuils': ['2_3', '3_3', '5_3'],
                                 'config_imgevent_flu_which_seuil': 2,
                                 'config_imgevent_flu_nb_seuils': 3,
                                 }

exp['knit005_201119_exp9_v1'] = {'ref': 'knit_005', 'date': 201119, 'nexp': 9,
                                 'version_raw': 1, 'version_work': 1,
                                 'vitesse': 0.005, 'Lw_0': 170, 'Lw_i': 210, 'Lw_max': 219.99,
                                 'fr_instron': 25, 'sursample': False,
                                 'delta_z': 1, 'delta_t_pict': 5,
                                 'nb_point_eff': 1,
                                 'prescycle': 2, 'mincycle': 2, 'maxcycle': 33,
                                 'mix_set': False, 'nb_set': 1, 'img': True, 'red': False,
                                 'nb_process': 15,
                                 'config_corr_fraction': 10,

                                 'config_scalarevent_flu_exposants': [5, 4, 4, 3, 3, 3],
                                 'config_scalarevent_flu_seuils': [3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 5e-3],
                                 'config_scalarevent_flu_save_seuils': ['3_5', '1_4', '3_4', '1_3', '3_3', '5_3'],
                                 'config_scalarevent_flu_nb_seuils': 6,
                                 'config_scalarevent_flu_which_seuil': 2,
                                 'config_scalarevent_flu_Sm_which_seuil': 5,
                                 'config_scalarevent_flu_nbclasses': 3,

                                 'config_imgevent_flu_slip_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_slip_seuils': [3e-4, 1e-3, 2e-3, 3e-3, 4e-3, 1e-2],
                                 'config_imgevent_flu_slip_save_seuils': ['3_4', '1_3', '2_3', '3_3', '4_3', '1_2'],
                                 'config_imgevent_flu_slip_which_seuil': 2,
                                 'config_imgevent_flu_slip_nb_seuils': 6,

                                 'config_imgevent_flu_sepvort_exposants': [4, 3, 3, 3, 3, 2],
                                 'config_imgevent_flu_sepvort_seuils': [3e-4, 2e-3, 3e-3, 4e-3, 5e-3, 1e-2],
                                 'config_imgevent_flu_sepvort_save_seuils': ['3_4', '2_3', '3_3', '4_3', '5_3', '1_2'],
                                 'config_imgevent_flu_sepvort_which_seuil': 2,
                                 'config_imgevent_flu_sepvort_nb_seuils': 6,

                                 'config_imgevent_flu_exposants': [3, 3, 3],
                                 'config_imgevent_flu_seuils': [2e-3, 3e-3, 5e-3],
                                 'config_imgevent_flu_save_seuils': ['2_3', '3_3', '5_3'],
                                 'config_imgevent_flu_which_seuil': 2,
                                 'config_imgevent_flu_nb_seuils': 3,
                                 }

exp['knit005_201119_exp10_v1'] = {'ref': 'knit_005', 'date': 201119, 'nexp': 10,
                                  'version_raw': 1, 'version_work': 1,
                                  'vitesse': 0.005, 'Lw_0': 170, 'Lw_i': 210, 'Lw_max': 219.99,
                                  'fr_instron': 25, 'sursample': False,
                                  'delta_z': 1, 'delta_t_pict': 5,
                                  'nb_point_eff': 1,
                                  'prescycle': 2, 'mincycle': 2, 'maxcycle': 33,
                                  'mix_set': False, 'nb_set': 1, 'img': False, 'red': False,
                                  'nb_process': 15,
                                  'config_corr_fraction': 10,

                                  'config_scalarevent_flu_exposants': [5, 4, 4, 3, 3, 3],
                                  'config_scalarevent_flu_seuils': [3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 5e-3],
                                  'config_scalarevent_flu_save_seuils': ['3_5', '1_4', '3_4', '1_3', '3_3', '5_3'],
                                  'config_scalarevent_flu_nb_seuils': 6,
                                  'config_scalarevent_flu_which_seuil': 2,
                                  'config_scalarevent_flu_Sm_which_seuil': 5,
                                  'config_scalarevent_flu_nbclasses': 3,

                                  'config_imgevent_flu_slip_exposants': [4, 3, 3, 3, 3, 2],
                                  'config_imgevent_flu_slip_seuils': [3e-4, 1e-3, 2e-3, 3e-3, 4e-3, 1e-2],
                                  'config_imgevent_flu_slip_save_seuils': ['3_4', '1_3', '2_3', '3_3', '4_3', '1_2'],
                                  'config_imgevent_flu_slip_which_seuil': 2,
                                  'config_imgevent_flu_slip_nb_seuils': 6,

                                  'config_imgevent_flu_sepvort_exposants': [4, 3, 3, 3, 3, 2],
                                  'config_imgevent_flu_sepvort_seuils': [3e-4, 2e-3, 3e-3, 4e-3, 5e-3, 1e-2],
                                  'config_imgevent_flu_sepvort_save_seuils': ['3_4', '2_3', '3_3', '4_3', '5_3', '1_2'],
                                  'config_imgevent_flu_sepvort_which_seuil': 2,
                                  'config_imgevent_flu_sepvort_nb_seuils': 6,

                                  'config_imgevent_flu_exposants': [3, 3, 3],
                                  'config_imgevent_flu_seuils': [2e-3, 3e-3, 5e-3],
                                  'config_imgevent_flu_save_seuils': ['2_3', '3_3', '5_3'],
                                  'config_imgevent_flu_which_seuil': 2,
                                  'config_imgevent_flu_nb_seuils': 3,
                                  }

exp['knit005_mix_v1'] = {'ref': 'knit_005', 'date': [201029, 201029, 201029, 201029, 201029, 201029, 201029, 201029,
                                                     201029, 201116, 201119, 201119, 201119, 201119, 201119, 201119,
                                                     201119, 201119, 201119, 201119],
                         'nexp': [1, 2, 3, 4, 5, 6, 7, 8, 9, 4, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'version_raw': 1, 'version_work': 1,
                         'vitesse': 0.005, 'Lw_0': 170, 'Lw_i': 210, 'Lw_max': 219.99,
                         'fr_instron': 25, 'sursample': False,
                         'delta_z': 1, 'delta_t_pict': 5,
                         'nb_point_eff': 1,
                         'prescycle': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
                         'mincycle': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
                         'maxcycle': [31, 39, 36, 36, 31, 31, 23, 27, 17, 39, 36, 39, 39, 39, 31, 39, 33, 31, 33, 33],
                         'mix_set': True, 'nb_set': 20, 'img': False, 'red': False,
                         'nb_process': 15,
                         'config_corr_fraction': 10,

                         'config_scalarevent_flu_exposants': [5, 4, 4, 3, 3, 3],
                         'config_scalarevent_flu_seuils': [3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 5e-3],
                         'config_scalarevent_flu_save_seuils': ['3_5', '1_4', '3_4', '1_3', '3_3', '5_3'],
                         'config_scalarevent_flu_nb_seuils': 6,
                         'config_scalarevent_flu_which_seuil': 2,
                         'config_scalarevent_flu_Sm_which_seuil': 5,
                         'config_scalarevent_flu_nbclasses': 3,

                         'config_imgevent_flu_slip_exposants': [4, 3, 3, 3, 3, 2],
                         'config_imgevent_flu_slip_seuils': [3e-4, 1e-3, 2e-3, 3e-3, 4e-3, 1e-2],
                         'config_imgevent_flu_slip_save_seuils': ['3_4', '1_3', '2_3', '3_3', '4_3', '1_2'],
                         'config_imgevent_flu_slip_which_seuil': 2,
                         'config_imgevent_flu_slip_nb_seuils': 6,

                         'config_imgevent_flu_sepvort_exposants': [4, 3, 3, 3, 3, 2],
                         'config_imgevent_flu_sepvort_seuils': [3e-4, 2e-3, 3e-3, 4e-3, 5e-3, 1e-2],
                         'config_imgevent_flu_sepvort_save_seuils': ['3_4', '2_3', '3_3', '4_3', '5_3', '1_2'],
                         'config_imgevent_flu_sepvort_which_seuil': 2,
                         'config_imgevent_flu_sepvort_nb_seuils': 6,

                         'config_imgevent_flu_exposants': [3, 3, 3],
                         'config_imgevent_flu_seuils': [2e-3, 3e-3, 5e-3],
                         'config_imgevent_flu_save_seuils': ['2_3', '3_3', '5_3'],
                         'config_imgevent_flu_which_seuil': 2,
                         'config_imgevent_flu_nb_seuils': 3,
                         }
